#!/usr/bin/env node
/* Make the public rate card (src/data.js) from the full, private one.

     node tools/public-data.js path/to/data.private.js > src/data.js

   Keeps what a client could see anyway: item IDs, categories, names, quantities, kit groups,
   the day rate to quote, packages, crew roles and rates, and New York's labor rules.
   Drops everything internal: resale values, low and high market rates and where they came
   from, confidence, notes, owner names, open questions, the buying list, the growth plan and
   the Google Sheet ID. Owner codes (M, C, S) stay because they are already in every item ID. */
const fs = require('fs');
const vm = require('vm');

const file = process.argv[2];
if (!file) { console.error('usage: node tools/public-data.js path/to/data.private.js > src/data.js'); process.exit(2); }
const ctx = {};
vm.runInNewContext(fs.readFileSync(file, 'utf8') + '\n;this.SNAPSHOT = SNAPSHOT;', ctx);
const S = ctx.SNAPSHOT;

// Two notes the app reads: per-lens pricing labels the storefront, transport keeps an item off it.
const keepNote = (n) => (/RATE IS PER LENS/.test(n || '') ? 'RATE IS PER LENS.' : /^Transport/.test(n || '') ? 'Transport, not billed.' : '');
const pub = {
  asOf: S.asOf,
  sheetId: '',
  owners: { M: { name: 'Owner M', short: 'M' }, C: { name: 'Owner C', short: 'C' }, S: { name: 'Owner S', short: 'S' } },
  poolNote: '',
  dataChecks: [],
  rows: S.rows.map((r) => [r[0], r[1], r[2], r[3], r[4], r[5], null, null, r[8], null, '', '', keepNote(r[12]), '', null]),
  packages: S.packages,
  labor: S.labor.map((l) => [l[0], l[1], null, l[3], null, '']),
  laborRules: S.laborRules,
  open: [], missing: [], growth: [], sequence: [],
};

const lines = (arr) => '[\n' + arr.map((x) => '    ' + JSON.stringify(x)).join(',\n') + '\n  ]';
const out = `/* Public rate card: item names, categories, quantities and the day rate to quote. Rates as of ${pub.asOf}.
   Generated by tools/public-data.js from the full rate card, which is kept private.
   Row shape: [id, category, item, qty, owner, kit, resaleEach, rateLow, rateRec, rateHigh, basis, confidence, notes, rentability, paybackDays] */
const SNAPSHOT = {
  asOf: ${JSON.stringify(pub.asOf)},
  sheetId: "",
  owners: ${JSON.stringify(pub.owners)},
  poolNote: "",
  dataChecks: [],
  rows: ${lines(pub.rows)},
  packages: ${lines(pub.packages)},
  labor: ${lines(pub.labor)},
  laborRules: ${lines(pub.laborRules)},
  open: [], missing: [], growth: [], sequence: []
};
`;
process.stdout.write(out);
